name: Docker Image CI

on:
  push:
    branches: [ "production" ]
  pull_request:
    branches: [ "production" ]

jobs:
  docker:
    runs-on: ubuntu-latest
    environment: production-env
    steps:
    - name: checkout?
      uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag dns-updater:production

    - name: Push the Docker Image
      run: docker push jeffkoo/dns-updater:production
